# Run tests on gitlab.pasteur.fr after new push
image: docker:latest
services:
  - docker:dind
  
variables:
  CRAW_HOME: /build

before_script:
 - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry-gitlab.pasteur.fr
 
build:
#    image: registry-gitlab.pasteur.fr/bneron/craw:centos7
    stage: test
    script:
         - docker run -v $CI_PROJECT_DIR:/build -e "CRAW_HOME=/build" registry-gitlab.pasteur.fr/bneron/craw:centos7 python3 /build/tests/run_tests.py -vvv
#        - python3 ${CRAW_HOME}/tests/run_tests.py -vvv
    except:
        - /^feat.*$/
