# Run tests on gitlab.pasteur.fr after new push
image: docker:latest
services:
  - docker:dind
  
variables:
  CRAW_HOME: ${CI_PROJECT_DIR}

before_script:
 - docker login -u bneron -p "$BNERON_CI_TOKEN" registry-gitlab.pasteur.fr
 
build:
#    image: registry-gitlab.pasteur.fr/bneron/craw:centos7
    stage: test
    script:
         - docker run registry-gitlab.pasteur.fr/bneron/craw:centos7 "python3 ${CRAW_HOME}/tests/run_tests.py -vvv"
#        - python3 ${CRAW_HOME}/tests/run_tests.py -vvv
    except:
        - /^feat.*$/
