stages:
  - test
  - coverage
  - release
  
variables:
  CRAW_HOME: ${CI_PROJECT_DIR}
  CRAW_VERSION: ${CI_COMMIT_REF_NAME}

testing:
  stage: test
  image: registry-gitlab.pasteur.fr/bneron/craw:centos-dep-0.6
  script:
      - python3 ${CI_PROJECT_DIR}/tests/run_tests.py -vvv
  except:
      - /^feat.*$/
      - /^fix.*$/

coverage:
  stage: coverage
  image: registry-gitlab.pasteur.fr/bneron/craw:coverage
  script:
    - cd ${CI_PROJECT_DIR}
    - coverage run --source=craw tests/run_tests.py --unit
    - coverage html

releasing:
  stage: release
  image: registry-gitlab.pasteur.fr/bneron/craw:release-0.6
  script:
    - cd ${CI_PROJECT_DIR}/doc/
    - make html
    - make latexpdf
    - cd ${CI_PROJECT_DIR}
    - python3 sdist
  artifacts:
    name: craw-"$CI_COMMIT_REF_NAME".tar.gz
    paths:
    - dist/craw*.tar.gz
  only:
    - tags
