# Run tests on gitlab.pasteur.fr after new push
  
variables:
  CRAW_HOME: ${CI_PROJECT_DIR}

testing:
    image: registry-gitlab.pasteur.fr/bneron/craw:centos7
    stage: test
    script:
        - python3 ${CI_PROJECT_DIR}/tests/run_tests.py -vvv
    except:
        - /^feat.*$/
